---
- hosts: all
  become: yes
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - name: Install apt packages
      ignore_errors: yes
      tags:
        - server_setup
      apt: name={{ item }} update_cache=yes state=installed
      with_items:
        - nodejs-legacy
        - build-essential
        - npm
        - git

    - name: Install n globally
      npm: name=n global=yes

    - name: Use node 6.8.0
      command: n 6.8.0

    - name: Update npm
      npm: name=npm global=yes

    - name: Create node symlink
      command: ln -sf /usr/local/n/versions/node/6.8.0/bin/node /usr/bin/node

    - name: Install pm2
      npm: name=pm2 global=yes

    - name: Install webpack globally
      npm: name=webpack path=/srv/monmach-client global=yes

    - name: Create the Github SSH public key file
      copy: src="config/id_avidreder_deploy.pub"
            dest="/root/.ssh/id_avidreder_deploy.pub"
            mode=0644

    - name: Create the Github SSH private key file
      copy: src="config/id_avidreder_deploy"
            dest="/root/.ssh/id_avidreder_deploy"
            mode=0600

    - name: Clone repo
      git:
        repo: ssh://git@github.com/avidreder/monmach-client.git
        dest: /srv/monmach-client
        version: master
        force: yes
        accept_hostkey: yes
        key_file: /root/.ssh/id_avidreder_deploy
      ignore_errors: yes

    - name: Install website deps
      npm: path=/srv/monmach-client
      ignore_errors: yes

    - name: fix owner/group
      ignore_errors: yes
      file:
        path: /srv/monmach-client/
        owner: root
        group: root

    - name: "Start example Node.js app."
      command: npm run deploy:dev chdir=/srv/monmach-client

    - name: "Start example Node.js app."
      command: pm2 kill chdir=/srv/monmach-client
      ignore_errors: yes

- hosts: vagrant
  become: yes
  tasks:
    - name: Run monmach-client
      command: pm2 start npm --no-automation --name "monmach-client" -- run vagrant chdir=/srv/monmach-client
      ignore_errors: yes

- hosts: development
  become: yes
  tasks:
    - name: Run monmach-client
      command: pm2 start npm --no-automation --name "monmach-client" -- run start chdir=/srv/monmach-client
      ignore_errors: yes
